/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n        query AllProjects {\n          projects {\n            id\n            key\n            name\n          }\n        }\n      ": typeof types.AllProjectsDocument,
    "\n            mutation PromoteBuild($input: PromoteBuildInput!) {\n              promoteBuild(input: $input) {\n                version {\n                  id\n                }\n                build {\n                  id\n                  channel\n                }\n              }\n            }\n          ": typeof types.PromoteBuildDocument,
    "\n      query SSRProject($project: String!) {\n        project(key: $project) {\n          key\n          name\n        }\n      }\n    ": typeof types.SsrProjectDocument,
    "\n        query ProjectFamilies($id: String!) {\n          project(key: $id) {\n            id\n            families {\n              id\n              key\n            }\n          }\n        }\n      ": typeof types.ProjectFamiliesDocument,
    "\n      query SSRFamily($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          family(key: $id) {\n            key\n          }\n        }\n      }\n    ": typeof types.SsrFamilyDocument,
    "\n        query Family($project: String!, $id: String!) {\n          project(key: $project) {\n            id\n            family(key: $id) {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n            versions(filterBy: { familyKey: $id }, first: 100, orderBy: { direction: DESC }) {\n              edges {\n                node {\n                  id\n                  key\n                  family {\n                    id\n                    key\n                  }\n                  support {\n                    status\n                    end\n                  }\n                }\n              }\n              pageInfo {\n                hasNextPage\n                endCursor\n              }\n            }\n          }\n        }\n      ": typeof types.FamilyDocument,
    "\n            mutation CreateFamily($input: CreateFamilyInput!) {\n              createFamily(input: $input) {\n                family {\n                  id\n                  key\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          ": typeof types.CreateFamilyDocument,
    "\n      query SSRVersion($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          version(key: $id) {\n            key\n            support {\n              status\n              end\n            }\n          }\n        }\n      }\n    ": typeof types.SsrVersionDocument,
    "\n        query Version($projectKey: String!, $versionKey: String!) {\n          project(key: $projectKey) {\n            id\n            gitRepository {\n              forge\n              host\n              owner\n              name\n              url\n              commitUrlTemplate\n            }\n            version(key: $versionKey) {\n              id\n              key\n              gitRepository {\n                forge\n                host\n                owner\n                name\n                url\n                commitUrlTemplate\n              }\n              support {\n                status\n                end\n              }\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n              family {\n                id\n                key\n                java {\n                  version {\n                    minimum\n                  }\n                  flags {\n                    recommended\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.VersionDocument,
    "\n        query VersionBuilds($projectKey: String!, $versionKey: String!, $after: String) {\n          project(key: $projectKey) {\n            id\n            version(key: $versionKey) {\n              id\n              builds(first: 25, after: $after, orderBy: { direction: DESC }) @_relayPagination {\n                edges {\n                  node {\n                    id\n                    number\n                    channel\n                    createdAt\n                    downloads {\n                      name\n                      size\n                      url\n                      checksums {\n                        sha256\n                      }\n                    }\n                    commits {\n                      sha\n                      message\n                    }\n                  }\n                }\n                pageInfo {\n                  hasNextPage\n                  hasPreviousPage\n                  startCursor\n                  endCursor\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.VersionBuildsDocument,
    "\n            mutation UpdateVersion($input: UpdateVersionInput!) {\n              updateVersion(input: $input) {\n                version {\n                  id\n                  key\n                  support {\n                    status\n                    end\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          ": typeof types.UpdateVersionDocument,
    "\n        query ProjectFamiliesWithMeta($projectKey: String!) {\n          project(key: $projectKey) {\n            families {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n          }\n        }\n      ": typeof types.ProjectFamiliesWithMetaDocument,
    "\n            mutation CreateVersion($input: CreateVersionInput!) {\n              createVersion(input: $input) {\n                version {\n                  key\n                  family {\n                    key\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          ": typeof types.CreateVersionDocument,
    "\n    query Webhooks {\n      webhooks {\n        id\n        url\n        createdAt\n        lastDeliveryStatus\n        lastDeliveryAt\n      }\n    }\n  ": typeof types.WebhooksDocument,
    "\n    mutation CreateWebhook($input: CreateWebhookInput!) {\n      createWebhook(input: $input) {\n        webhook {\n          id\n          url\n        }\n        secret\n      }\n    }\n  ": typeof types.CreateWebhookDocument,
    "\n    mutation DeleteWebhook($input: DeleteWebhookInput!) {\n      deleteWebhook(input: $input) {\n        ok\n      }\n    }\n  ": typeof types.DeleteWebhookDocument,
};
const documents: Documents = {
    "\n        query AllProjects {\n          projects {\n            id\n            key\n            name\n          }\n        }\n      ": types.AllProjectsDocument,
    "\n            mutation PromoteBuild($input: PromoteBuildInput!) {\n              promoteBuild(input: $input) {\n                version {\n                  id\n                }\n                build {\n                  id\n                  channel\n                }\n              }\n            }\n          ": types.PromoteBuildDocument,
    "\n      query SSRProject($project: String!) {\n        project(key: $project) {\n          key\n          name\n        }\n      }\n    ": types.SsrProjectDocument,
    "\n        query ProjectFamilies($id: String!) {\n          project(key: $id) {\n            id\n            families {\n              id\n              key\n            }\n          }\n        }\n      ": types.ProjectFamiliesDocument,
    "\n      query SSRFamily($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          family(key: $id) {\n            key\n          }\n        }\n      }\n    ": types.SsrFamilyDocument,
    "\n        query Family($project: String!, $id: String!) {\n          project(key: $project) {\n            id\n            family(key: $id) {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n            versions(filterBy: { familyKey: $id }, first: 100, orderBy: { direction: DESC }) {\n              edges {\n                node {\n                  id\n                  key\n                  family {\n                    id\n                    key\n                  }\n                  support {\n                    status\n                    end\n                  }\n                }\n              }\n              pageInfo {\n                hasNextPage\n                endCursor\n              }\n            }\n          }\n        }\n      ": types.FamilyDocument,
    "\n            mutation CreateFamily($input: CreateFamilyInput!) {\n              createFamily(input: $input) {\n                family {\n                  id\n                  key\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          ": types.CreateFamilyDocument,
    "\n      query SSRVersion($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          version(key: $id) {\n            key\n            support {\n              status\n              end\n            }\n          }\n        }\n      }\n    ": types.SsrVersionDocument,
    "\n        query Version($projectKey: String!, $versionKey: String!) {\n          project(key: $projectKey) {\n            id\n            gitRepository {\n              forge\n              host\n              owner\n              name\n              url\n              commitUrlTemplate\n            }\n            version(key: $versionKey) {\n              id\n              key\n              gitRepository {\n                forge\n                host\n                owner\n                name\n                url\n                commitUrlTemplate\n              }\n              support {\n                status\n                end\n              }\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n              family {\n                id\n                key\n                java {\n                  version {\n                    minimum\n                  }\n                  flags {\n                    recommended\n                  }\n                }\n              }\n            }\n          }\n        }\n      ": types.VersionDocument,
    "\n        query VersionBuilds($projectKey: String!, $versionKey: String!, $after: String) {\n          project(key: $projectKey) {\n            id\n            version(key: $versionKey) {\n              id\n              builds(first: 25, after: $after, orderBy: { direction: DESC }) @_relayPagination {\n                edges {\n                  node {\n                    id\n                    number\n                    channel\n                    createdAt\n                    downloads {\n                      name\n                      size\n                      url\n                      checksums {\n                        sha256\n                      }\n                    }\n                    commits {\n                      sha\n                      message\n                    }\n                  }\n                }\n                pageInfo {\n                  hasNextPage\n                  hasPreviousPage\n                  startCursor\n                  endCursor\n                }\n              }\n            }\n          }\n        }\n      ": types.VersionBuildsDocument,
    "\n            mutation UpdateVersion($input: UpdateVersionInput!) {\n              updateVersion(input: $input) {\n                version {\n                  id\n                  key\n                  support {\n                    status\n                    end\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          ": types.UpdateVersionDocument,
    "\n        query ProjectFamiliesWithMeta($projectKey: String!) {\n          project(key: $projectKey) {\n            families {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n          }\n        }\n      ": types.ProjectFamiliesWithMetaDocument,
    "\n            mutation CreateVersion($input: CreateVersionInput!) {\n              createVersion(input: $input) {\n                version {\n                  key\n                  family {\n                    key\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          ": types.CreateVersionDocument,
    "\n    query Webhooks {\n      webhooks {\n        id\n        url\n        createdAt\n        lastDeliveryStatus\n        lastDeliveryAt\n      }\n    }\n  ": types.WebhooksDocument,
    "\n    mutation CreateWebhook($input: CreateWebhookInput!) {\n      createWebhook(input: $input) {\n        webhook {\n          id\n          url\n        }\n        secret\n      }\n    }\n  ": types.CreateWebhookDocument,
    "\n    mutation DeleteWebhook($input: DeleteWebhookInput!) {\n      deleteWebhook(input: $input) {\n        ok\n      }\n    }\n  ": types.DeleteWebhookDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query AllProjects {\n          projects {\n            id\n            key\n            name\n          }\n        }\n      "): (typeof documents)["\n        query AllProjects {\n          projects {\n            id\n            key\n            name\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation PromoteBuild($input: PromoteBuildInput!) {\n              promoteBuild(input: $input) {\n                version {\n                  id\n                }\n                build {\n                  id\n                  channel\n                }\n              }\n            }\n          "): (typeof documents)["\n            mutation PromoteBuild($input: PromoteBuildInput!) {\n              promoteBuild(input: $input) {\n                version {\n                  id\n                }\n                build {\n                  id\n                  channel\n                }\n              }\n            }\n          "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query SSRProject($project: String!) {\n        project(key: $project) {\n          key\n          name\n        }\n      }\n    "): (typeof documents)["\n      query SSRProject($project: String!) {\n        project(key: $project) {\n          key\n          name\n        }\n      }\n    "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query ProjectFamilies($id: String!) {\n          project(key: $id) {\n            id\n            families {\n              id\n              key\n            }\n          }\n        }\n      "): (typeof documents)["\n        query ProjectFamilies($id: String!) {\n          project(key: $id) {\n            id\n            families {\n              id\n              key\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query SSRFamily($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          family(key: $id) {\n            key\n          }\n        }\n      }\n    "): (typeof documents)["\n      query SSRFamily($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          family(key: $id) {\n            key\n          }\n        }\n      }\n    "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query Family($project: String!, $id: String!) {\n          project(key: $project) {\n            id\n            family(key: $id) {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n            versions(filterBy: { familyKey: $id }, first: 100, orderBy: { direction: DESC }) {\n              edges {\n                node {\n                  id\n                  key\n                  family {\n                    id\n                    key\n                  }\n                  support {\n                    status\n                    end\n                  }\n                }\n              }\n              pageInfo {\n                hasNextPage\n                endCursor\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query Family($project: String!, $id: String!) {\n          project(key: $project) {\n            id\n            family(key: $id) {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n            versions(filterBy: { familyKey: $id }, first: 100, orderBy: { direction: DESC }) {\n              edges {\n                node {\n                  id\n                  key\n                  family {\n                    id\n                    key\n                  }\n                  support {\n                    status\n                    end\n                  }\n                }\n              }\n              pageInfo {\n                hasNextPage\n                endCursor\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation CreateFamily($input: CreateFamilyInput!) {\n              createFamily(input: $input) {\n                family {\n                  id\n                  key\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          "): (typeof documents)["\n            mutation CreateFamily($input: CreateFamilyInput!) {\n              createFamily(input: $input) {\n                family {\n                  id\n                  key\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      query SSRVersion($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          version(key: $id) {\n            key\n            support {\n              status\n              end\n            }\n          }\n        }\n      }\n    "): (typeof documents)["\n      query SSRVersion($project: String!, $id: String!) {\n        project(key: $project) {\n          key\n          name\n          version(key: $id) {\n            key\n            support {\n              status\n              end\n            }\n          }\n        }\n      }\n    "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query Version($projectKey: String!, $versionKey: String!) {\n          project(key: $projectKey) {\n            id\n            gitRepository {\n              forge\n              host\n              owner\n              name\n              url\n              commitUrlTemplate\n            }\n            version(key: $versionKey) {\n              id\n              key\n              gitRepository {\n                forge\n                host\n                owner\n                name\n                url\n                commitUrlTemplate\n              }\n              support {\n                status\n                end\n              }\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n              family {\n                id\n                key\n                java {\n                  version {\n                    minimum\n                  }\n                  flags {\n                    recommended\n                  }\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query Version($projectKey: String!, $versionKey: String!) {\n          project(key: $projectKey) {\n            id\n            gitRepository {\n              forge\n              host\n              owner\n              name\n              url\n              commitUrlTemplate\n            }\n            version(key: $versionKey) {\n              id\n              key\n              gitRepository {\n                forge\n                host\n                owner\n                name\n                url\n                commitUrlTemplate\n              }\n              support {\n                status\n                end\n              }\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n              family {\n                id\n                key\n                java {\n                  version {\n                    minimum\n                  }\n                  flags {\n                    recommended\n                  }\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query VersionBuilds($projectKey: String!, $versionKey: String!, $after: String) {\n          project(key: $projectKey) {\n            id\n            version(key: $versionKey) {\n              id\n              builds(first: 25, after: $after, orderBy: { direction: DESC }) @_relayPagination {\n                edges {\n                  node {\n                    id\n                    number\n                    channel\n                    createdAt\n                    downloads {\n                      name\n                      size\n                      url\n                      checksums {\n                        sha256\n                      }\n                    }\n                    commits {\n                      sha\n                      message\n                    }\n                  }\n                }\n                pageInfo {\n                  hasNextPage\n                  hasPreviousPage\n                  startCursor\n                  endCursor\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query VersionBuilds($projectKey: String!, $versionKey: String!, $after: String) {\n          project(key: $projectKey) {\n            id\n            version(key: $versionKey) {\n              id\n              builds(first: 25, after: $after, orderBy: { direction: DESC }) @_relayPagination {\n                edges {\n                  node {\n                    id\n                    number\n                    channel\n                    createdAt\n                    downloads {\n                      name\n                      size\n                      url\n                      checksums {\n                        sha256\n                      }\n                    }\n                    commits {\n                      sha\n                      message\n                    }\n                  }\n                }\n                pageInfo {\n                  hasNextPage\n                  hasPreviousPage\n                  startCursor\n                  endCursor\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation UpdateVersion($input: UpdateVersionInput!) {\n              updateVersion(input: $input) {\n                version {\n                  id\n                  key\n                  support {\n                    status\n                    end\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          "): (typeof documents)["\n            mutation UpdateVersion($input: UpdateVersionInput!) {\n              updateVersion(input: $input) {\n                version {\n                  id\n                  key\n                  support {\n                    status\n                    end\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n        query ProjectFamiliesWithMeta($projectKey: String!) {\n          project(key: $projectKey) {\n            families {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n          }\n        }\n      "): (typeof documents)["\n        query ProjectFamiliesWithMeta($projectKey: String!) {\n          project(key: $projectKey) {\n            families {\n              id\n              key\n              java {\n                version {\n                  minimum\n                }\n                flags {\n                  recommended\n                }\n              }\n            }\n          }\n        }\n      "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n            mutation CreateVersion($input: CreateVersionInput!) {\n              createVersion(input: $input) {\n                version {\n                  key\n                  family {\n                    key\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          "): (typeof documents)["\n            mutation CreateVersion($input: CreateVersionInput!) {\n              createVersion(input: $input) {\n                version {\n                  key\n                  family {\n                    key\n                  }\n                  java {\n                    version {\n                      minimum\n                    }\n                    flags {\n                      recommended\n                    }\n                  }\n                }\n              }\n            }\n          "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query Webhooks {\n      webhooks {\n        id\n        url\n        createdAt\n        lastDeliveryStatus\n        lastDeliveryAt\n      }\n    }\n  "): (typeof documents)["\n    query Webhooks {\n      webhooks {\n        id\n        url\n        createdAt\n        lastDeliveryStatus\n        lastDeliveryAt\n      }\n    }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation CreateWebhook($input: CreateWebhookInput!) {\n      createWebhook(input: $input) {\n        webhook {\n          id\n          url\n        }\n        secret\n      }\n    }\n  "): (typeof documents)["\n    mutation CreateWebhook($input: CreateWebhookInput!) {\n      createWebhook(input: $input) {\n        webhook {\n          id\n          url\n        }\n        secret\n      }\n    }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation DeleteWebhook($input: DeleteWebhookInput!) {\n      deleteWebhook(input: $input) {\n        ok\n      }\n    }\n  "): (typeof documents)["\n    mutation DeleteWebhook($input: DeleteWebhookInput!) {\n      deleteWebhook(input: $input) {\n        ok\n      }\n    }\n  "];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;